apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
  namespace: default
data:
  appsettings.json: |-
    {
      "Hosts": [
        {
          "Slug": "gcp",
          "Type": 3,
          "Backend": "cis_fti_group"
        },
        {
          "Slug": "proxy",
          "Type": 2,
          "Backend": "http://imgsrv.kolb-digital.de/"
        }
      ],

      "App": {
        "VersionName": "now with google storage bucket .net core 3.1",
        "Build": "1.0.23"
      }
    }
